name: Deploy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
      - name: Build before deploy
        run: npm run predeploy
      - name: Deploy to production
        run: npm run deploy
