name: Deploy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Build before deploy
        working-directory: "../../"
        run: echo pwd && npm run build && gh-pages -d build
      #- name: Deploy to production
      #  run: npm run deploy
